language: php

sudo: false

git:
    depth: 1

matrix:
    include:
        - php: 5.6
        - php: 7.0
    fast_finish: true

branches:
    only:
        - master
        - develop

script:
    - sh ./.travis/shell/php_lint.sh
